name: Test

on:
  push:
  pull_request:

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: docker run --rm -tv $(pwd):/src -w /src/test -e BUILD_NAME=ACCEPTANCE ghdl/vunit:llvm make all

  Formal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: docker run --rm -tv $(pwd):/src -w /src/formal -e BUILD_NAME=ACCEPTANCE ghdl/synth:formal make all
